### ISSUE TITLE
addArrowhead function not rendering

### ISSUE THREAD

**Issue by Chris-Has** [trafficonese/leaflet.extras2#43]
Using R 4.1.2 and tried both CRAN and dev version of package.
Example renders a blank map. No error msgs. Other functions work.
library(leaflet)
leaflet() %>%
  addArrowhead(data = atlStorms2005)

**Comment by trafficonese** [comment]
Interesting, it is working in Shiny with R 4.20 but not in the Rstudio Viewer. 
Somehow it is not appending the JS-libraries, so this errors pops up in the console:
`L.polyline(...).arrowheads is not a function`

**Comment by trafficonese** [comment]
I think the problem is related to [this](https://stackoverflow.com/questions/43507180/rstudio-viewer-throws-error).

The RStudio browser apparently doesnt accept JavaScript ES6. 

Unfortunately nothing I can do here. I opened an issue at Rstudio https://github.com/rstudio/rstudio/issues/11900

**Comment by trafficonese** [comment]
Apparently this is fixed in the newer RStudio versions.
https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/windows/

I just succesfully tried with Rstudio 2022.11.0 Build 166

**Comment by Chris-Has** [comment]
Great! Thanks trafficonese
